import { json } from '@sveltejs/kit';
import { createFile, verifyClientOwnership } from '$lib/server/services';
import { createFileSchema } from '$lib/validations';
import {
	unauthorized,
	notFound,
	badRequest,
	handleZodError,
	handleApiError
} from '$lib/server/errors';
import type { RequestHandler } from './$types';

export const POST: RequestHandler = async ({ locals, request }) => {
	if (!locals.user) return unauthorized();

	const body = await request.json();
	const parsed = createFileSchema.safeParse(body);

	if (!parsed.success) {
		return handleZodError(parsed.error);
	}

	const owns = await verifyClientOwnership(locals.user.id, parsed.data.clientId);
	if (!owns) return notFound('Client');

	// The storagePath is generated by /api/files/upload-url and must live under
	// the caller's own prefix. Reject anything else so a caller can't create a
	// file row pointing at another tenant's object (which the service-role
	// Supabase client would happily sign a download URL for).
	const expectedPrefix = `${locals.user.id}/${parsed.data.clientId}/`;
	if (!parsed.data.storagePath.startsWith(expectedPrefix)) {
		return badRequest('Invalid storage path');
	}

	try {
		const file = await createFile(locals.user.id, parsed.data);
		return json(file, { status: 201 });
	} catch (error) {
		return handleApiError(error);
	}
};
